exclude: ^(requirements|.*static|.*assets)
default_stages: [ commit ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [ commit ]
      - id: trailing-whitespace
        stages: [ commit ]
      - id: check-merge-conflict
      - id: double-quote-string-fixer

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--skip-string-normalization', '--skip-magic-trailing-comma', '--line-length', '120']
